kind: swin-upernet
backbone=dict(
        embed_dim=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        ape=False,
        drop_path_rate=0.3,
        patch_norm=True,
        use_checkpoint=False)

decode_head=dict(
        in_channels=[96, 192, 384, 768],
        num_classes=150)

